---
title: "Leaflet & Mapbox"
author: "John Coene"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Leaflet & Mapbox}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(echarts4r)

e_common(
    font_family = "Raleway"
)
```

Leaflet only works with `e_scatter` and `e_effect_scatter`.

## Scatter

```{r}
url <- "https://echarts.apache.org/examples/data-gl/asset/data/population.json"
data <- jsonlite::fromJSON(url)
data <- as.data.frame(data)
names(data) <- c("lon", "lat", "value")
data$value <- log(data$value)

data |> 
  e_charts(lon) |> 
  e_leaflet() |>
  e_leaflet_tile() |>  
  e_scatter(lat, size = value, coord_system = "leaflet")
```

## Mapbox

You will need [mapbox](https://www.mapbox.com/) token.

```{r, echo = TRUE, eval = FALSE}
data |> 
  e_charts(lon) |> 
  e_mapbox(
    token = "YOUR_TOKEN",
    style = "mapbox://styles/mapbox/dark-v9"
  ) |> 
  e_bar_3d(lat, value, coord_system = "mapbox") |> 
  e_visual_map(value)
```

```{r, echo = FALSE}
data |> 
  e_charts(lon) |> 
  e_mapbox(
    token = "pk.eyJ1IjoiamNvZW5lcCIsImEiOiJjamwyYXJyMjExb2R0M3FxcDlmemg2czFiIn0.OL6qEEADz5qBjhKecwgBdg",
    style = "mapbox://styles/mapbox/dark-v9"
  ) |> 
  e_bar_3d(lat, value, coord_system = "mapbox") |> 
  e_visual_map(value)
```