---
title: "Proxies"
author: "John Coene"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Proxies}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(echarts4r)
```

Proxies easily allow you to interact with a plot without having to redraw the whole chart. Note that all proxies end in `_p` like `e_showtip_p`.

```{r, eval = FALSE}
library(shiny)
  
ui <- fluidPage(
  actionButton("add", "Add Data"),
  echarts4rOutput("plot")
)

server <- function(input, output, session){

  data <- data.frame(x = rnorm(10, 5, 3), y = rnorm(10, 50, 12))
  
  react <- eventReactive(input$add, {
    set.seed(sample(1:1000, 1))
    data.frame(x = rnorm(10, 5, 2), y = rnorm(10, 50, 10))
  })
  
  output$plot <- renderEcharts4r({
    data %>% 
     e_charts(x) %>% 
     e_scatter(y)
  })
  
  observeEvent(input$add, {
    echarts4rProxy("plot") %>% 
      e_append1_p(0, react(), x, y)
  })
  
}

shinyApp(ui, server)
```