---
title: "Themes"
author: "John Coene"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Themes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(echarts4r)

e_common(
    font_family = "Raleway"
)
```

You can easily customise the appearance of your chart using one of the 13 themes provided, or even build you own theme: use the online [theme builder](http://echarts.baidu.com/download-theme.html) to create your own.

## default

```{r}
p <- USArrests %>% 
  dplyr::mutate(
    State = row.names(.),
    Rape = -Rape
  ) %>% 
  e_charts(State) %>% 
  e_line(Murder) %>% 
  e_area(Rape, name = "Sick basterd", x_index = 1) %>%  # second y axis
  e_title("Your plot", "Subtext", sublink = "https://john-coene.com") %>% 
  e_x_axis(1, show = FALSE) # hide scond X Axis

p # default plot
```

## dark

```{r}
p %>% e_theme("dark")
```

## vintage

```{r}
p %>% e_theme("vintage")
```

## westeros

```{r}
p %>% e_theme("westeros")
```

## essos

```{r}
p %>% e_theme("essos")
```

## wonderland

```{r}
p %>% e_theme("wonderland")
```

## walden

```{r}
p %>% e_theme("walden")
```

## chalk

```{r}
p %>% e_theme("chalk")
```

## infographic

```{r}
p %>% e_theme("infographic")
```

## macarons

```{r}
p %>% e_theme("macarons")
```

## roma

```{r}
p %>% e_theme("roma")
```

## shine

```{r}
p %>% e_theme("shine")
```

## purple-passion

```{r}
p %>% e_theme("purple-passion")
```

## halloween

```{r}
p %>% e_theme("halloween")
```

## custom

```{r}
p %>% e_theme_custom('{"color":["#ff715e","#ffaf51"]}')
```